import Topbar from "@/components/shadcn/Topbar";
import Sidebar from "@/components/shadcn/Sidebar";
import type { Metadata } from "next";
import Bottombar from "@/components/shadcn/Bottombar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-inter w-full md:flex`}>
        <Topbar/>
        <Sidebar/>
            <main className="w-full flex h-auto absolute top-16 md:top-0 md:left-[270px] md:w-[50%] justify-center pb-10">
                {children}
            </main>
        <Bottombar/>
    </body>
    </html>
  );
}